### ISSUE TITLE
Error trying with `npm run build`

### ISSUE THREAD

**Issue by criloz** [Feper07/calculadora#1]
When you run the `npm run build`, those errors appears in the console

![Screenshot from 2023-01-09 00-09-26](https://user-images.githubusercontent.com/1408540/211244308-68fd6a13-bcc9-40f3-a8b6-5a793c70c5b0.png)

Please fix them and upload the changes to GitHub

**Comment by Feper07** [comment]
fixed: 

https://github.com/Feper07/calculadora/commit/204a400638844a85822624d33a1ac79c2dc9a015
